#!/usr/bin/env bash
# Shared helpers for optional real-Mailu integration scripts.

integration_dir() {
	cd "$(dirname "${BASH_SOURCE[0]}")" && pwd
}

repo_root() {
	cd "$(integration_dir)/../.." && pwd
}

state_file() {
	printf '%s/.state.env\n' "$(integration_dir)"
}

require_real_opt_in() {
	if [[ ${MAILUOPS_REAL_MAILU:-} != 1 ]]; then
		printf 'Refusing real Mailu integration without MAILUOPS_REAL_MAILU=1.\n' >&2
		exit 1
	fi
}

require_cmd() {
	local cmd=$1
	command -v "$cmd" >/dev/null 2>&1 || {
		printf 'missing required command: %s\n' "$cmd" >&2
		exit 1
	}
}

load_state() {
	local file
	file=$(state_file)
	[[ -f $file ]] || {
		printf 'integration state file not found: %s\n' "$file" >&2
		exit 1
	}
	# The state file is generated by up.sh using shell-quoted values only.
	# shellcheck source=/dev/null
	. "$file"
	[[ -n ${PROJECT:-} && -n ${TEST_ROOT:-} ]] || {
		printf 'integration state file is missing PROJECT or TEST_ROOT: %s\n' "$file" >&2
		exit 1
	}
}

assert_safe_state() {
	[[ ${PROJECT:-} == mailuops-it-* ]] || {
		printf 'unsafe integration project name: %s\n' "${PROJECT:-}" >&2
		exit 1
	}
	[[ ${TEST_ROOT:-} == "$HOME"/.cache/mailuops-it.* ]] || {
		printf 'unsafe integration test root: %s\n' "${TEST_ROOT:-}" >&2
		exit 1
	}
	[[ -f $TEST_ROOT/.mailuops-integration-root ]] || {
		printf 'missing integration root marker: %s\n' "$TEST_ROOT/.mailuops-integration-root" >&2
		exit 1
	}
}

port_993_free() {
	! ss -ltn 2>/dev/null | awk 'NR > 1 && $4 ~ /(^|:)993$/ { found=1 } END { exit found ? 0 : 1 }'
}
